### ISSUE TITLE
[TODO] Quelques trucs que je voudrais avant la première version

### ISSUE THREAD

**Issue by GoudronViande24** [Artivain/artibot#1]
- [x] Faire un bon readme
  - [x] Mettre des informations sur le projet
  - [x] Mettre des informations sur comment participer, les issues, les pull requests etc
  - [x] Mettre notre Discord
  - [x] Présenter Artivain vite fait
- [x] Finir le module global Twitch
- [x] #4
- [x] Commande info dans le module core
- [x] Corriger les interactions message et user qui ne fonctionnent juste pas pour l'instant
- [x] S'assurer que la config est passée correctement à tous les modules pour l'uniformité
- [x] Terminer l'interaction Informations sur l'utilisateur
  - [x] Depuis combien de temps il est sur le serveur
  - [x] Est-il le fondateur?
  - [x] Est-il un des contributeurs de Artibot?

**Comment by GoudronViande24** [comment]
Complété avec le dernier commit: e409e4772d1bac379bac588a9e76cc359bd7da16

**Comment by GoudronViande24** [comment]
@all-contributors please add @GoudronViande24 for code

**Comment by GoudronViande24** [comment]
@all-contributors please add @GoudronViande24 for code
